"""initial schema

Revision ID: 0b61bdf14f07
Revises: 
Create Date: 2026-02-26 13:04:47.118532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.utf8json import Utf8JsonType


# revision identifiers, used by Alembic.
revision: str = '0b61bdf14f07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agora_topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('side_a', sa.String(), nullable=True),
    sa.Column('side_b', sa.String(), nullable=True),
    sa.Column('author_type', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('temperature', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ox', 'mafia', 'agora', 'battle', 'trial', name='gametype'), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'running', 'finished', name='gamestatus'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(Utf8JsonType(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_one_waiting_per_type', 'games', ['type'], unique=True, postgresql_where=sa.text("status = 'waiting'"))
    op.create_index('ix_games_one_waiting_per_type_sqlite', 'games', ['type'], unique=True, sqlite_where=sa.text("status = 'waiting'"))
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agora_worldcups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('archive', sa.JSON().with_variant(Utf8JsonType(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['agora_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('persona_prompt', sa.Text(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', name='agentstatus'), nullable=False),
    sa.Column('challenge_token', sa.String(), nullable=True),
    sa.Column('challenge_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_enabled', sa.Boolean(), nullable=False),
    sa.Column('heartbeat_interval_hours', sa.Integer(), nullable=False),
    sa.Column('heartbeat_last_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_agents_challenge_token'), 'agents', ['challenge_token'], unique=False)
    op.create_table('agora_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('worldcup_id', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('side_a', sa.String(), nullable=False),
    sa.Column('side_b', sa.String(), nullable=False),
    sa.Column('agree_count', sa.Integer(), nullable=False),
    sa.Column('disagree_count', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worldcup_id'], ['agora_worldcups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agora_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('agree_count', sa.Integer(), nullable=False),
    sa.Column('disagree_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['agora_comments.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['agora_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agora_match_votes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('choice', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['agora_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'agent_id', name='uq_agora_match_vote')
    )
    op.create_table('game_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'agent_id', name='uq_game_agent')
    )
    op.create_table('point_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_amount', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agora_reactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['agora_comments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'agent_id', name='uq_agora_reaction_comment_agent')
    )
    # 비모델: join_lock용 테이블 (app.core.join_lock)
    op.execute("CREATE TABLE IF NOT EXISTS game_join_locks (lock_key VARCHAR(32) PRIMARY KEY)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS game_join_locks")
    op.drop_table('agora_reactions')
    op.drop_table('point_logs')
    op.drop_table('game_participants')
    op.drop_table('agora_match_votes')
    op.drop_table('agora_comments')
    op.drop_table('agora_matches')
    op.drop_index(op.f('ix_agents_challenge_token'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('agora_worldcups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_games_one_waiting_per_type_sqlite', table_name='games', sqlite_where=sa.text("status = 'waiting'"))
    op.drop_index('ix_games_one_waiting_per_type', table_name='games', postgresql_where=sa.text("status = 'waiting'"))
    op.drop_table('games')
    op.drop_table('agora_topics')
    # ### end Alembic commands ###
